### ISSUE TITLE
icmp support

### ISSUE THREAD

**Issue by FlowerWrong** [yinghuocho/gotun2socks#4]
`ping baidu.com`

not support icmp

```
2016/12/07 22:48:41 Unsupported packet: protocol 1
2016/12/07 22:48:42 Unsupported packet: protocol 1
2016/12/07 22:48:43 Unsupported packet: protocol 1
2016/12/07 22:48:44 Unsupported packet: protocol 1
2016/12/07 22:48:45 Unsupported packet: protocol 1
2016/12/07 22:48:46 Unsupported packet: protocol 1
2016/12/07 22:48:47 Unsupported packet: protocol 1
2016/12/07 22:48:48 Unsupported packet: protocol 1
2016/12/07 22:48:49 Unsupported packet: protocol 1
2016/12/07 22:48:50 Unsupported packet: protocol 1
2016/12/07 22:48:51 Unsupported packet: protocol 1
```

**Comment by yinghuocho** [comment]
I don't come out a simple and clean way to support ICMP. See previous disucssion in #2.
If we can figure out a simpler way, I will do it. Right now, I don't feel it is urgent to suport ICMP.

**Comment by FlowerWrong** [comment]
Why not just relay the icmp packet? if ping baidu, just relay the icmp packet to baidu's DNS result IP address. This may need add more route tables.

**Comment by yinghuocho** [comment]
This is not general. Support ICMP means that we need to make ICMP works for any IP address.

**Comment by FlowerWrong** [comment]
Maybe you can design it as vpn+tun2socks, if it is ip layer or below, go through vpn, or go through tun2socks. on socks 5 proxy, you can do more like surge rules. _The problem is I do not know socks 5 support ftp and other protocols or not_(yes, it supports all protocol up network layer). Also it is difficult to setup a vpn and a socks5 server on the same vps.

Oh! I think it is incorrect.

**Comment by TongxiJi** [comment]
@yinghuocho  Now,tcp and udp works fine on Windows.
But when we use it to play some games(such as Battlefield and LOL) with ICMP data,the game will go wrong.
So supporting about  icmp may be important.

Anyway,thank you very much and you are a good man.

**Comment by yinghuocho** [comment]
thank you for the appreciation. Are you chaining gotun2socks with shadowsocks? What is your solution for the games that need ICMP connectivity, VPN ?

**Comment by TongxiJi** [comment]
Yes,with shadowsocks.
Without ICMP relay, though the game works, the ping value of the game is not  correct(not  all games  but  some).
Maybe we can specify  as server as a reference but this is not the final solution.

Sorry for not replying to you in time.

**Comment by FlowerWrong** [comment]
@yinghuocho transform icmp ping to tcp ping? aha

**Comment by yinghuocho** [comment]
@FlowerWrong Supporting ICMP on tun2socks needs to have a specific program/process on server-side that receives ICMP messages from client and relay to remote, also relay the response back. I have some idea how to implement this feature, just don't have sufficient time right now.
